# Generated by Django 2.0.3 on 2018-03-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='album_logo',
            new_name='document_logo',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='name',
            new_name='document_name',
        ),
    ]
