# Generated by Django 2.0.3 on 2018-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0002_auto_20180331_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='document_logo',
        ),
        migrations.AddField(
            model_name='documents',
            name='document_link',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
