# Generated by Django 2.0.3 on 2018-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0003_auto_20180505_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_biotech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_cse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_mech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Documents_bca',
        ),
    ]
