# Generated by Django 2.0.3 on 2018-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0004_auto_20180506_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_name', models.CharField(max_length=50)),
            ],
        ),
    ]
