# Generated by Django 2.0.3 on 2018-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0006_auto_20180519_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='mech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Documents_it',
            new_name='bca',
        ),
        migrations.RenameModel(
            old_name='Documents_mech',
            new_name='biotech',
        ),
        migrations.RenameModel(
            old_name='Documents_bca',
            new_name='civil',
        ),
        migrations.RenameModel(
            old_name='Documents_electronics',
            new_name='electronics',
        ),
        migrations.DeleteModel(
            name='Documents_biotech',
        ),
        migrations.DeleteModel(
            name='Documents_civil',
        ),
        migrations.RenameField(
            model_name='bca',
            old_name='document_link',
            new_name='bca_link',
        ),
        migrations.RenameField(
            model_name='bca',
            old_name='document_name',
            new_name='bca_name',
        ),
        migrations.RenameField(
            model_name='biotech',
            old_name='document_link',
            new_name='biotech_link',
        ),
        migrations.RenameField(
            model_name='biotech',
            old_name='document_name',
            new_name='biotech_name',
        ),
        migrations.RenameField(
            model_name='civil',
            old_name='document_link',
            new_name='civil_link',
        ),
        migrations.RenameField(
            model_name='civil',
            old_name='document_name',
            new_name='civil_name',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='document_link',
            new_name='electronics_link',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='document_name',
            new_name='electronics_name',
        ),
    ]
