# Generated by Django 2.0.3 on 2018-05-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0008_auto_20180519_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cse',
            name='cse_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
