# Generated by Django 2.0.3 on 2018-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0009_cse_cse_link_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='bca',
            name='bca_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='biotech',
            name='biotech_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='civil',
            name='civil_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='electronics_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='it',
            name='it_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mech',
            name='mech_link_end',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
