# Generated by Django 2.0.3 on 2018-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0011_auto_20180520_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='strings',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
