# Generated by Django 2.0.3 on 2018-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0013_auto_20180523_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='bca5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bca_name', models.CharField(max_length=250)),
                ('bca_link_mid', models.CharField(max_length=250)),
                ('bca_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bca6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bca_name', models.CharField(max_length=250)),
                ('bca_link_mid', models.CharField(max_length=250)),
                ('bca_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bca7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bca_name', models.CharField(max_length=250)),
                ('bca_link_mid', models.CharField(max_length=250)),
                ('bca_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bca8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bca_name', models.CharField(max_length=250)),
                ('bca_link_mid', models.CharField(max_length=250)),
                ('bca_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='biotech8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotech_name', models.CharField(max_length=250)),
                ('biotech_link_mid', models.CharField(max_length=250)),
                ('biotech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_name', models.CharField(max_length=250)),
                ('civil_link_mid', models.CharField(max_length=250)),
                ('civil_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='electronics8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_name', models.CharField(max_length=250)),
                ('electronics_link_mid', models.CharField(max_length=250)),
                ('electronics_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=250)),
                ('it_link_mid', models.CharField(max_length=250)),
                ('it_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mech8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(max_length=250)),
                ('mech_link_mid', models.CharField(max_length=250)),
                ('mech_link_end', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='civil',
            new_name='bca1',
        ),
        migrations.RenameModel(
            old_name='bca',
            new_name='bca2',
        ),
        migrations.RenameModel(
            old_name='biotech',
            new_name='bca3',
        ),
        migrations.RenameModel(
            old_name='electronics',
            new_name='bca4',
        ),
        migrations.RenameModel(
            old_name='it',
            new_name='it1',
        ),
        migrations.RenameModel(
            old_name='mech',
            new_name='it2',
        ),
        migrations.RenameField(
            model_name='bca1',
            old_name='civil_link_end',
            new_name='bca_link_end',
        ),
        migrations.RenameField(
            model_name='bca1',
            old_name='civil_link_mid',
            new_name='bca_link_mid',
        ),
        migrations.RenameField(
            model_name='bca1',
            old_name='civil_name',
            new_name='bca_name',
        ),
        migrations.RenameField(
            model_name='bca3',
            old_name='biotech_link_end',
            new_name='bca_link_end',
        ),
        migrations.RenameField(
            model_name='bca3',
            old_name='biotech_link_mid',
            new_name='bca_link_mid',
        ),
        migrations.RenameField(
            model_name='bca3',
            old_name='biotech_name',
            new_name='bca_name',
        ),
        migrations.RenameField(
            model_name='bca4',
            old_name='electronics_link_end',
            new_name='bca_link_end',
        ),
        migrations.RenameField(
            model_name='bca4',
            old_name='electronics_link_mid',
            new_name='bca_link_mid',
        ),
        migrations.RenameField(
            model_name='bca4',
            old_name='electronics_name',
            new_name='bca_name',
        ),
        migrations.RenameField(
            model_name='it2',
            old_name='mech_link_end',
            new_name='it_link_end',
        ),
        migrations.RenameField(
            model_name='it2',
            old_name='mech_link_mid',
            new_name='it_link_mid',
        ),
        migrations.RenameField(
            model_name='it2',
            old_name='mech_name',
            new_name='it_name',
        ),
    ]
