# Generated by Django 2.0.3 on 2018-05-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperbank', '0014_auto_20180523_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bca7',
        ),
        migrations.DeleteModel(
            name='bca8',
        ),
    ]
